account/urls.py
from django.urls import path

from .views import SignupView, MyLoginView, MyLogoutView


app_name = "account"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", MyLoginView.as_view(), name="login"),
    # path("logoff/", MyLoginView.as_view(), name="logoff"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
]

api/urls.py
from django.urls import path

from .views import RoomApi

urlpatterns = [
    path("room/", RoomApi.as_view()),
]

chat/urls.py
from django.urls import path
from .websocket import ChatConsumer, RoomListConsumer
from django.urls import include, path
from rest_framework import routers

from .views import RoomList, RoomDetails

app_name = "chat"

# router = routers.DefaultRouter()
# router.register(r"heroes", views.HeroViewSet)

urlpatterns = [
    path("", RoomList.as_view(), name="main"),
    path("room/<int:room_id>/", RoomDetails.as_view(), name="room_details"),
    path("api/", include("api.urls")),
    # path("<int:room_id>/leave", LeaveRoom.as_view(), name="leave_room"),
]


websocket_urlpatterns = [
    path("ws/room/<int:room_id>/<str:username>/", ChatConsumer.as_asgi()),
    path("ws/roomlist/<str:username>/", RoomListConsumer.as_asgi()),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("chat.urls")),
    path("account/", include("account.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    # path("api-auth/", include("rest_framework.urls")),
]


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/bootstrap.min.css' %} rel="stylesheet" />
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Чат с комнатами</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% with request.resolver_match.url_name as url_name %}
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'post_list' %}active{% endif %}" href={% url 'chat:main' %}>Список комнат</a>
                            </li>
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'account_logout' %}active{% endif %}" href={% url 'account:logout' %}>Выход</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'account_login' %}active{% endif %}" href={% url 'account:login' %}>Вход</a>
                                </li>
                            {% endif %}
                        {% endwith %}
                    </ul>
                </div>
            </div>
        </nav>

        <br>
        <div class="row d-flex justify-content-center">
            <div class="col-md-8">
                {% block content %}
                {% endblock content %}
            </div>
        </div>

        
        <script src={% static 'js/jquery-3.5.1.slim.min.js' %}></script>
        <script src={% static 'js/bootstrap.min.js' %}></script>
        <script src={% static 'js/bootstrap.bundle.min.js' %}></script>
        <script src={% static 'js/scripts.js' %}></script>
        <script src={% static 'js/chat.js' %}></script>
    </body>
    </html>
    